sudo: required

services:
    - docker

before_install:
    - docker build -t gadirlih/client-dev-test -f Dockerfile.dev ./client

script:
    - docker run -e CI=true gadirlih/client-dev-test npm run test

after_success:
    - docker build -t gadirlih/multi-client ./client
    - docker build -t gadirlih/multi-nginx ./nginx
    - docker build -t gadirlih/multi-server ./server
    - docker build -t gadirlih/multi-worker ./worker
    # Login to docker hub
    - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
    # Push prod images to docker hub
    - docker push gadirlih/multi-client
    - docker push gadirlih/multi-nginx
    - docker push gadirlih/multi-server
    - docker push gadirlih/multi-worker
